"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { SERVICES } from "@/lib/constants";

const providers = [
  { id:"sofia", initials:"SV", name:"Sofia V.", role:"Home cleaner", category:"cleaning", rate:24, location:"Oud-West", rating:"4.9", reviews:38, tags:["Deep cleans","Eco products"] },
  { id:"aisha", initials:"AK", name:"Aisha K.", role:"Housekeeper", category:"housekeeping", rate:22, location:"De Pijp", rating:"5.0", reviews:21, tags:["Laundry","Organisation"] },
  { id:"luca", initials:"LM", name:"Luca M.", role:"Electrician", category:"electrical", rate:42, location:"Oost", rating:"4.8", reviews:17, tags:["Certified","Small repairs"] },
  { id:"youssef", initials:"YB", name:"Youssef B.", role:"Plumber", category:"plumbing", rate:39, location:"Noord", rating:"4.9", reviews:29, tags:["Emergency jobs","Installations"] },
  { id:"daan", initials:"DB", name:"Daan B.", role:"Mover & helper", category:"moving", rate:31, location:"West", rating:"4.7", reviews:12, tags:["Van available","Heavy lifting"] },
  { id:"maya", initials:"MS", name:"Maya S.", role:"Move-out cleaner", category:"cleaning", rate:26, location:"Centrum", rating:"4.9", reviews:44, tags:["Move-out","Flexible times"] }
];

export default function HomePage() {
  const [category, setCategory] = useState("all");
  const [showBooking, setShowBooking] = useState(false);
  const [selected, setSelected] = useState(providers[0]);
  const filtered = useMemo(() => category === "all" ? providers : providers.filter((p) => p.category === category), [category]);
  const book = (provider: typeof providers[number]) => { setSelected(provider); setShowBooking(true); };

  return <>
    <header><div className="shell nav"><Link className="brand" href="/"><span className="mark">·</span>homehelp</Link><nav className="links"><a href="#find-help">Find help</a><a href="#how-it-works">How it works</a><a href="#become-a-pro">Become a pro</a></nav><div className="nav-actions"><Link className="btn btn-ghost" href="/auth">Sign in</Link><a className="btn btn-primary" href="#find-help">Find a helper</a></div></div></header>
    <main>
      <section className="hero"><div className="shell hero-grid"><div><div className="kicker">Home services / Amsterdam</div><h1>Good help,<br /><em>close to home.</em></h1><p className="lead">Book trusted local professionals for the jobs that keep life moving—from a deep clean to a last-minute move. <strong>Simple hourly pricing. Real people. One place.</strong></p><div className="actions"><a className="btn btn-primary" href="#find-help">Find a helper →</a><a className="btn btn-secondary" href="#become-a-pro">Offer your services</a></div><p className="note">Launching in Amsterdam · Providers are reviewed before going live</p></div><div className="search-card"><div className="search-head"><div><div className="kicker">Start here</div><p>What do you need help with?</p></div><span className="live">● Live in Amsterdam</span></div><div className="grid grid-2"><div className="field full"><label htmlFor="service">Service</label><select id="service" className="select" value={category} onChange={(e) => { setCategory(e.target.value); document.getElementById("find-help")?.scrollIntoView({ behavior:"smooth" }); }}><option value="all">All home services</option>{SERVICES.map((s) => <option key={s.slug} value={s.slug}>{s.label}</option>)}</select></div><div className="field"><label htmlFor="area">Area</label><input id="area" className="input" value="Amsterdam" readOnly /></div><div className="field"><label htmlFor="when">When</label><select id="when" className="select"><option>As soon as possible</option><option>This week</option><option>Next week</option></select></div></div><a className="btn btn-primary full-btn" href="#find-help">See available helpers</a></div></div></section>
      <div className="strip"><div className="shell strip-grid"><div className="strip-item"><span className="icon">✓</span>Providers reviewed before going live</div><div className="strip-item"><span className="icon">€</span>Clear hourly rates, no surprises</div><div className="strip-item"><span className="icon">↗</span>Support when plans change</div></div></div>
      <section className="section" id="find-help"><div className="shell"><div className="section-head"><div><div className="kicker">The marketplace</div><h2>Find someone who<br />can get it done.</h2><p className="section-copy">Browse local professionals by service and book a time that works for you. Every profile shows the details that matter.</p></div><a className="link" href="#how-it-works">See how booking works →</a></div><div className="chips"><button className={`chip ${category === "all" ? "active" : ""}`} onClick={() => setCategory("all")}>All services</button>{SERVICES.map((s) => <button key={s.slug} className={`chip ${category === s.slug ? "active" : ""}`} onClick={() => setCategory(s.slug)}>{s.label}</button>)}</div><div className="providers">{filtered.map((p) => <article className="provider" key={p.id}><div className="provider-top"><div className="avatar">{p.initials}</div><div className="provider-meta"><div className="provider-name">{p.name} <span style={{ color:"var(--green)" }}>●</span></div><div className="provider-role">{p.role}</div><div className="provider-location">{p.location} · Amsterdam</div></div></div><div className="provider-body"><div className="tags">{p.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div><div className="provider-bottom"><div><div className="rate">€{p.rate} <small>/ hour</small></div><div className="rating">★ <strong>{p.rating}</strong> · {p.reviews} reviews</div></div><button className="btn btn-primary" onClick={() => book(p)}>Book</button></div></article>)}</div></div></section>
      <section className="section band" id="how-it-works"><div className="shell two-col"><div><div className="kicker">Booking, without the back-and-forth</div><h2>From “I need help”<br />to “all done.”</h2><div className="steps"><div className="step"><span className="step-number">1</span><div><h3>Tell us what you need</h3><p>Choose a service, area, and preferred time in a few clicks.</p></div></div><div className="step"><span className="step-number">2</span><div><h3>Choose your professional</h3><p>Compare rates, reviews, experience, and availability.</p></div></div><div className="step"><span className="step-number">3</span><div><h3>Request the booking</h3><p>The provider confirms the job, and payment is handled securely.</p></div></div></div></div><div className="card booking"><div className="booking-head"><div><div className="kicker">Your request</div><h3>Book a home cleaner</h3></div><span>Step 2 of 3</span></div><div className="mini"><div className="avatar">SV</div><div><strong>Sofia V.</strong><p>Home cleaner · €24 / hour</p></div></div><label>Pick a time</label><div className="times"><button className="time">Tue 10:00</button><button className="time selected">Wed 14:00</button><button className="time">Thu 09:00</button><button className="time">Fri 16:00</button></div><div className="price"><span>2 hours × €24</span><span>€48.00</span></div><div className="price"><span>HomeHelp service fee</span><span>€5.76</span></div><div className="price total"><span>Total</span><span>€53.76</span></div><button className="btn btn-primary full-btn" onClick={() => book(providers[0])}>Request booking</button></div></div></section>
      <section className="section" id="become-a-pro"><div className="shell pro-grid"><div><div className="kicker">For local professionals</div><h2>Turn your time<br />into extra income.</h2><p className="lead">Set your own hourly rate, choose the jobs you want, and meet more customers in your neighbourhood. HomeHelp handles discovery, booking, and payment.</p><div className="earnings"><div><strong>€24+</strong><span>Typical hourly rate</span></div><div><strong>100%</strong><span>You choose your hours</span></div></div><div className="fee">Pilot setup: HomeHelp takes a 12% platform fee from each completed booking. Providers are invite-only and approved before going live.</div></div><div className="card onboard"><div className="onboard-head"><div><div className="kicker">Join HomeHelp</div><h3>Build your provider profile</h3><p>Provider onboarding and approval are built into the MVP.</p></div><span className="live">3 min</span></div><div className="steps-tabs"><span className="tab active">01 · Basics</span><span className="tab">02 · Profile</span><span className="tab">03 · Rates</span></div><div className="grid grid-2"><div className="field"><label>First name</label><input className="input" placeholder="e.g. Sofia" /></div><div className="field"><label>City</label><input className="input" value="Amsterdam" readOnly /></div><div className="field full"><label>Main service</label><select className="select"><option>Cleaning</option><option>Housekeeping</option><option>Electrical</option><option>Plumbing</option><option>Moving</option></select></div></div><Link className="btn btn-primary full-btn" href="/provider/onboarding">Continue to provider onboarding →</Link></div></div></section>
    </main>
    <footer className="footer"><div className="shell footer-row"><span>© 2026 HomeHelp Amsterdam · MVP</span><div className="footer-links"><a href="#find-help">Find help</a><a href="/provider/onboarding">Become a pro</a><Link href="/auth">Sign in</Link></div></div></footer>
    {showBooking && <div style={{ position:"fixed", inset:0, zIndex:50, background:"rgba(17,20,26,.55)", display:"grid", placeItems:"center", padding:20 }} onClick={() => setShowBooking(false)}><div className="card" style={{ width:"min(480px,100%)", padding:25 }} onClick={(e) => e.stopPropagation()}><div className="kicker">Booking request</div><h3 style={{ marginTop:5 }}>Request a booking with {selected.name}</h3><p style={{ color:"var(--muted)", fontSize:14 }}>The provider confirms the job before payment is captured.</p><div className="card" style={{ boxShadow:"none", padding:14, margin:"18px 0" }}><div className="price"><span>Service</span><strong>{selected.role}</strong></div><div className="price"><span>Time</span><strong>Wednesday · 14:00</strong></div><div className="price total"><span>Estimated total</span><strong>€{(selected.rate * 2 * 1.12).toFixed(2)}</strong></div></div><Link className="btn btn-primary full-btn" href="/auth?next=/checkout">Continue to secure checkout</Link><button className="btn btn-secondary full-btn" onClick={() => setShowBooking(false)}>Not now</button></div></div>}
  </>;
}